# Site settings
title: Rane Gowan | Web Developer
email: ranegowan@gmail.com
url: https://rgowan.github.io
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Rane Gowan

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Rane_Gowan
  - title: github
    url: https://github.com/rgowan
  - title: linkedin
    url: https://uk.linkedin.com/in/ranegowan

# Build settings
markdown: kramdown
permalink: pretty
